# Generated by Django 5.0.7 on 2024-07-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('may', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='userinfo',
        ),
    ]
