# Generated by Django 5.0.7 on 2024-08-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('may', '0002_alter_userinfo_options_alter_userinfo_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
