# Generated by Django 5.0.7 on 2024-08-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('may', '0003_userinfo_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_superuser',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
