# Generated by Django 4.2.14 on 2024-08-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('may', '0004_userinfo_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
